name: build

on: [push]

jobs:
  build-executable-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v5
        with:
          context: .
          file: "Dockerfile"
          tags: citest_build:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false

      - name: Run citest build container
        uses: addnab/docker-run-action@v3
        with:
          image: citest_build:latest
          # run: poetry run nox -s build
          # options: -v "$PWD:${{ github.workspace }}"

      - uses: actions/upload-artifact@v4
        with:
          name: dist-ubuntu-latest
          path: "file1.txt"
          # path: "${{ github.workspace }}/file1-copy.txt"
