on: [push]

jobs:
  docker_test:
    runs-on: ubuntu-latest
    name: Test docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Hello world action step
        uses: ./.github/actions/run-docker/

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: workspace_artifacts
          path: ${{ github.workspace }}
